### ISSUE TITLE
Match isn't being passed to cloned anchors

### ISSUE THREAD

**Issue by AsaAyers** [georgeOsdDev/react-anchorify-text#13]
```jsx
const ExternalLink = (props) => (
    <a href={props.url} target="_blank" rel="nofollow">
        {JSON.stringify(props)}
    </a>
)

                <AnchorifyText text={message}>
                    <ExternalLink />
                </AnchorifyText>
```

`props` contains a `.url`, but nothing else. 

I think you forgot to compile your code before the last release:

https://github.com/georgeOsdDev/react-anchorify-text/blob/master/lib/components/AnchorifyText.js#L70
https://github.com/georgeOsdDev/react-anchorify-text/blob/master/src/components/AnchorifyText.js#L31

**Comment by georgeOsdDev** [comment]
Fixed with #14
